### ISSUE TITLE
Create auth token at startup

### ISSUE THREAD

**Issue by cjmcgraw** [netsandbox/docker-rt#10]
This container is not very useful for testing against RT5 instances if there is no easy way to programmatically generate an auth token.

Can you please add functionality that established an auth token from a known environmental variable?

Use case:

```
#docker-compose.yml

version: "3.8"

services:

    my_webservice:
        ...
        environment:
            - RT_AUTH_TOKEN: <some-random-static-hex>
  
   request_tracker:
       image: netsandbox/request-tracker:5.0
       environment:
           - RT_AUTH_TOKEN: <same-random-static-hex>
```

This would be very nice to have

As a work around I am willing to generate one at startup with my own dockerfile if possible though. But it seems like it requires user interaction of some kind

**Comment by cjmcgraw** [comment]
For those potentially interested here is a work around to get this working.

1. Bring the container up
2. Use the UI to generate the auth token (following their docs)
3. Save the authtoken to a local file. It is now permanent
4. `docker cp ${container}:/opt/rt5/var/rt5 initial-database.sqlite`
5. Add the following Dockerfile you build from:

```
#Dockerfile
FROM netsandbox/request-tracker:5.0
COPY initial-database.sqlite /opt/rt5/var/rt5
```

6. Mount the auth token across to your other webservice

```
#docker-compose.yml

version: "3.8"

services:

    my_webservice:
        ...
        volumes:
            - type: bind
              source: ./request_tracker/auth_tokens/
              target: /auth_tokens
        ...

    request_tracker:
        build: ./request_tracker
```
7. In the code for your webservice access the file mounted at `/auth_tokens/*`

This is hacky AF but definitely works to circumvent this problem
